@{
    RootModule        = 'PSGuerrilla.psm1'
    ModuleVersion     = '2.22.0'
    GUID              = 'f7a3b2c1-4d5e-6f78-9a0b-1c2d3e4f5a6b'
    Author            = 'Jim Tyler, Microsoft MVP'
    CompanyName       = 'Jim Tyler'
    Copyright         = '(c) 2026 Jim Tyler. All rights reserved.'
    Description       = 'Security assessment, threat detection, and continuous monitoring module for Google Workspace, Active Directory, and Microsoft cloud environments. Includes Google Workspace compromise assessment with 23 detection signals, Active Directory reconnaissance (205 security checks across 15 categories including transitive Tier-0 attack-path analysis, NTLM-relay preconditions, Tier-0 hygiene, telemetry posture, and adversary tradecraft indicators), Entra ID / Azure / Intune / M365 infiltration audit (158 checks), and continuous monitoring across all four theaters (Entra ID sign-in risk, AD baseline monitoring, M365 audit log monitoring). Supports alerting via SendGrid, Mailgun, Twilio SMS, Teams, Slack, generic webhooks, PagerDuty, Pushover, Syslog (CEF/LEEF), and Windows Event Log.'
    PowerShellVersion = '7.0'
    FunctionsToExport = @(
        'Invoke-Recon'
        'Invoke-Surveillance'
        'Invoke-Watchtower'
        'Invoke-Wiretap'
        'Invoke-Lookout'
        'Get-DeadDrop'
        'Send-Signal'
        'Send-SignalSendGrid'
        'Send-SignalMailgun'
        'Send-SignalTwilio'
        'Send-SignalTeams'
        'Send-SignalSlack'
        'Send-SignalWebhook'
        'Send-SignalPagerDuty'
        'Send-SignalPushover'
        'Send-SignalSyslog'
        'Send-SignalEventLog'
        'Send-SignalDigest'
        'Set-Safehouse'
        'Test-Safehouse'
        'Get-Safehouse'
        'Register-Patrol'
        'Unregister-Patrol'
        'Get-Patrol'
        'Update-ThreatIntel'
        'Invoke-ReconDemo'
        'Invoke-Fortification'
        'Invoke-Reconnaissance'
        'Invoke-Infiltration'
        'Invoke-Campaign'
        'Get-GuerrillaScore'
        'Get-GuerrillaMaturity'
        'Get-QuickWins'
        'Get-ComplianceCrosswalk'
        'Export-BudgetJustification'
        'Export-ExecutiveSummary'
        'Export-TechnicalReport'
        'Export-RemediationPlaybook'
        'Export-RemediationScripts'
        'Set-RiskAcceptance'
        'Get-RiskAcceptance'
        'Get-TrendReport'
        'Export-ReportPdf'
        'Export-Dashboard'
        'Export-BloodHoundData'
        'Show-Guerrilla'
    )
    CmdletsToExport   = @()
    VariablesToExport  = @()
    AliasesToExport    = @(
        # PSRecon -> PSGuerrilla rename aliases
        'Invoke-GoogleRecon'
        'Get-ReconAlerts'
        'Send-ReconAlert'
        'Send-ReconAlertSendGrid'
        'Send-ReconAlertMailgun'
        'Send-ReconAlertTwilio'
        'Set-ReconConfig'
        'Get-ReconConfig'
        'Register-ReconScheduledTask'
        'Unregister-ReconScheduledTask'
        'Get-ReconScheduledTask'
        # Theater-disambiguating aliases
        'Invoke-WorkspaceRecon'
        'Invoke-ADRecon'
        'Invoke-CloudRecon'
    )
    FormatsToProcess   = @('PSGuerrilla.format.ps1xml')
    PrivateData = @{
        PSData = @{
            Tags       = @('GoogleWorkspace', 'ActiveDirectory', 'EntraID', 'AzureAD', 'Intune', 'M365', 'Security', 'CompromiseAssessment', 'IncidentResponse', 'ThreatDetection', 'ADSecurity', 'CloudSecurity', 'NTLMRelay', 'TierZero', 'GUI', 'WPF', 'PSGuerrilla')
            LicenseUri = 'https://creativecommons.org/licenses/by/4.0/'
            ProjectUri = 'https://guerrilla.army'
            ReleaseNotes = 'v2.22.0: New CISA SCuBA baseline crosswalk: 55 Entra/M365 checks now carry scuba compliance tags mapping to live CISA ScubaGear baseline policy IDs (MS.AAD/EXO/SHAREPOINT/TEAMS/DEFENDER/POWERPLATFORM). Get-ComplianceCrosswalk -Framework SCUBA emits per-policy mapping rows; the Executive Summary auto-shows a SCUBA gap chip. ~76% of the assessable SCuBA baseline mapped (72 of 95 policies; Power BI unassessed - no Power BI checks yet). Baseline IDs pulled live from cisagov/ScubaGear, not fabricated. Also EIDSCA tagging (Maester P4.2): 8 checks tagged, Get-ComplianceCrosswalk -Framework EIDSCA. New-AuditFinding now carries Scuba + Eidsca arrays through to findings (the one engine change needed). Honest: only tagged checks produce SCuBA rows; 23 baseline policies + all Power BI are not yet assessed (feeds a future net-new-check release). Tag-only: no check logic/scoring/count changes (473 checks, 46 public functions). Test verify-scuba-crosswalk.ps1 (12/12). v2.21.0: New Attack-Path Cartography (Get-GuerrillaCartographyHtml): a native in-report SVG node-link map of escalation routes to Tier-0, laid out left-to-right by longest-path rank. Non-privileged starts red, already-privileged amber, Tier-0 objectives gold; shared targets converge into one node. Built entirely from attack-path chain data already in findings - no extra collection, no external tool - so it renders self-contained. Added to the AD reconnaissance, Campaign, and Technical reports (renders only when AD attack paths exist; capped at 25 paths). This is the cartography half of the PingCastle plan; unlike PingCastles built-in map it is free and sits alongside the BloodHound export. The PingCastle plan is now COMPLETE (maturity model, transitive attack-path engine, full-domain ACL collection, BloodHound export, cartography). Report-only: no engine/check/scoring changes. 46 public functions, check counts unchanged. Samples regenerated. Test verify-report-sections.ps1 (24/24). See CHANGELOG.md for v2.21.0 and earlier.'
        }
    }
}
